FROM ghcr.io/actions/actions-runner:2.320.0
USER root
RUN apt-get update -qy \
    && apt-get install -y --no-install-recommends --fix-missing curl \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y --no-install-recommends --fix-missing \
    build-essential \
    libssl-dev \
    libmysqlclient-dev \
    tzdata \
    nodejs \
    graphviz \
    libxss1 \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libnss3 \
    libxcomposite1 \
    libxrandr2 \
    libu2f-udev \
    fonts-liberation \
    libgbm1 \
    xdg-utils \
    imagemagick \
    rsync \
    && npm install --global yarn \
    && rm -rf /var/lib/apt/lists/*
USER runner
