FROM ghcr.io/actions/actions-runner:2.320.0
USER root
RUN apt-get update -qy \
    && apt-get install -y --no-install-recommends --fix-missing \
    build-essential \
    libssl-dev \
    libmysqlclient-dev \
    nodejs \
    npm \
    tzdata \
    rsync \
    && npm install --global yarn \
    && rm -rf /var/lib/apt/lists/*
USER runner
